---
- name: Deploy app using Docker
  hosts: all
  become: yes

  tasks:
    - name: Install required packages
      yum:
        name:
          - docker
          - python3
          - python3-pip
        state: present

    - name: Install Docker Python SDK
      pip:
        name: docker
        executable: pip3

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull image from Docker Hub
      community.docker.docker_image:
        name: shwetaraut815/myapp
        tag: latest
        source: pull

    - name: Run container
      community.docker.docker_container:
        name: app-cont
        image: shwetaraut815/myapp:latest
        state: started
        ports:
          - "8080:8080"
